# Docker compose file for jupyterhub - ldap integration
---
version: "2.2"
services:
  openldap:
    image: osixia/openldap
    container_name: openldap
    hostname: openldap
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_TLS_VERIFY_CLIENT=try
    volumes:
      - .\ldap\lib:/var/lib/ldap
      - .\ldap\slapd.d\:/etc/ldap/slapd.d
      
  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - 6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap

  jupyterhub:
    image: jupyterhub/jupyterhub
    container_name: jupyterhub
    hostname: jupyterhub
    command: 
      - /bin/bash
      - -c 
      - |
        cp /tmp/add_dir/jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
        jupyterhub
    ports:
      - 7443:443
      - 8000:8000
    volumes:
      - c:\Users\KomlosiLas\Documents\GitHub\docker-jupyterhub-ldap\add_dir:/tmp/add_dir

        